host: "localhost"
port: 6333
similarity_top_k: 3
similarity_cutoff: 0.98
collection_name: "loveroom"
api_key: "ac89ee8d-ba2a-4e31-bad7-021cf411c673"
model_name: "doubao-embedding-text-240715"
chat_model_name: "doubao-seed-1-6-250615"

Desensitization_prompt: "校验 {text} 所有的名字用化名代替(小美 小张)"
Evaluation_prompt: "校验{des_result}"
roll_time: 3